### **SF Salaries Exercise**

Welcome to a quick exercise for you to practice your pandas skills! We will be using the SF Salaries Dataset from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

### **Load Necessary libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### **Read Salaries.csv as a dataframe called sal.**

In [ ]:
sal = pd.read_csv(r'/content/Salaries.csv')

### **Check the head of the DataFrame.**

In [ ]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

### **Check nan/missing values**

In [ ]:
sum([True,False,True])

2

In [ ]:
sal.isna().sum()
#sal.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

### **Total records , rows and columns**

In [ ]:
sal.shape

(148654, 13)

### **check feature names**

In [ ]:
sal.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

### **drop Notes and Status columns bcz they have 100% missing values**

In [ ]:
sal.drop(columns=['Notes','Status'],inplace=True)

In [ ]:
#check new shape
sal.shape

(148654, 11)

In [ ]:
#check columns
sal.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Agency'],
      dtype='object')

### **fill BasePay NaN by using some technique**

In [ ]:
#sal.BasePay --> Series
#sal['BasePay'] --> Series
#sal[['BasePay']] --> df

# fill NaN by 0
#sal.BasePay.fillna(0)

# fill NaN by -1
#sal.BasePay.fillna(-1)

# fill NaN by mean() of BasePay column
#sal.BasePay.fillna(round(sal.BasePay.mean(),2))
mn = round(sal.BasePay.mean(),2)
sal.BasePay.fillna(mn)
# we can use inplace to store the changes permnt.

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148649         0.00
148650     66325.45
148651     66325.45
148652     66325.45
148653         0.00
Name: BasePay, Length: 148654, dtype: float64


Missing value Strateries:
- mean(): when features are contineous or discrete ex. Salary,Age,Cost/Price
- mode(): when features are categorical ex. post, branch, gender

In [ ]:
r = pd.DataFrame([np.nan,100,np.nan,200,300,np.nan,400,np.nan])
r

       0
0    NaN
1  100.0
2    NaN
3  200.0
4  300.0
5    NaN
6  400.0
7    NaN

In [ ]:
#pad/ffill: forward filling
r.fillna(method='ffill')

       0
0    NaN
1  100.0
2  100.0
3  200.0
4  300.0
5  300.0
6  400.0
7  400.0

In [ ]:
#bfill/backfill: backward filling
r.fillna(method='bfill')

       0
0  100.0
1  100.0
2  200.0
3  200.0
4  300.0
5  400.0
6  400.0
7    NaN

In [ ]:
sal.BasePay.fillna(method='bfill',inplace=True)
# save the changes with inplace

In [ ]:
sal.isna().sum()

Id                      0
EmployeeName            0
JobTitle                0
BasePay                 0
OvertimePay             4
OtherPay                4
Benefits            36163
TotalPay                0
TotalPayBenefits        0
Year                    0
Agency                  0
dtype: int64

## **What is the average BasePay ?**

In [ ]:
sal.BasePay.mean()

66096.98294987017

## **What is the highest amount of OvertimePay in the dataset ?**

In [ ]:
sal.OvertimePay.max()

245131.88

## **Fetch record of Highest paid employee**

In [ ]:
sal.TotalPayBenefits.max()

567595.43

In [ ]:
sal[sal.TotalPayBenefits == 567595.43]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,San Francisco

In [ ]:
#Fetch name of highest Paid employee
high_paid = sal[sal.TotalPayBenefits == 567595.43]
high_paid['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

## **Check for duplicate records**

In [ ]:
sum(sal.duplicated())

0

## **What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).**

In [ ]:
sal[sal.EmployeeName == 'JOSEPH DRISCOLL']

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140546.86,97868.77,31909.28,NaN,270324.91,270324.91,2011,San Francisco

In [ ]:
sal[sal.EmployeeName == 'JOSEPH DRISCOLL'].JobTitle

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [ ]:
#fetch JobTitle and TotalPay of this guy
sal[sal.EmployeeName == 'JOSEPH DRISCOLL'][['JobTitle','TotalPay']]

                     JobTitle   TotalPay
24  CAPTAIN, FIRE SUPPRESSION  270324.91

In [ ]:
sal[sal.EmployeeName == 'Joseph Driscoll']

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
36198,36199,Joseph Driscoll,"Captain, Fire Suppression",145658.98,114513.29,28743.36,42919.16,288915.63,331834.79,2012,San Francisco

Sort the sal on the basis of OtherPay